[metadata]
format.version = "1.1"

[versions]
edc = "v1.0.0-SNAPSHOT"
googleApiGax = "2.68.0"
googleApisIam = "v2-rev20240108-2.0.0"
googleCloudBom = "26.59.0"

[libraries]
edc-junit = { module = "org.eclipse.edc:junit", version.ref = "edc" }
edc-lib-util = { module = "org.eclipse.edc:util-lib", version.ref = "edc" }
edc-spi-core = { module = "org.eclipse.edc:core-spi", version.ref = "edc" }
edc-spi-dataplane = { module = "org.eclipse.edc:data-plane-spi", version.ref = "edc" }
edc-spi-transfer = { module = "org.eclipse.edc:transfer-spi", version.ref = "edc" }
edc-spi-validator = { module = "org.eclipse.edc:validator-spi", version.ref = "edc" }

# Google dependencies
googlecloud-bom = { module = "com.google.cloud:libraries-bom", version.ref = "googleCloudBom" }
googleapis-iam = { module = "com.google.apis:google-api-services-iam", version.ref = "googleApisIam"}
googlecloud-bigquery = { module = "com.google.cloud:google-cloud-bigquery" }
googlecloud-core = { module = "com.google.cloud:google-cloud-core" }
googlecloud-gax = { module = "com.google.api:gax" , version.ref = "googleApiGax"}
googlecloud-iam-admin = { module = "com.google.cloud:google-iam-admin" }
googlecloud-iam-credentials = { module = "com.google.cloud:google-cloud-iamcredentials" }
googlecloud-secretmanager = { module = "com.google.cloud:google-cloud-secretmanager" }
googlecloud-storage = { module = "com.google.cloud:google-cloud-storage" }

[bundles]

[plugins]
edc-build = { id = "org.eclipse.edc.edc-build", version = "1.5.2" }
