name: "Setup Gradle"
description: "Setup Gradle"
runs:
  using: "composite"
  steps:
    - uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Gradle cache
      uses: gradle/gradle-build-action@v2
