name: Run Tests

on:
  workflow_call:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ main, release/*, bugfix/* ]
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'CODEOWNERS'
      - 'LICENSE'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  Checkstyle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Run Checkstyle
        run: ./gradlew checkstyleMain checkstyleTest

  Dependency-Check:
    uses: eclipse-edc/.github/.github/workflows/dependency-check.yml@main
    secrets: inherit

  Unit-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Run unit tests
        run: ./gradlew test

  Component-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Component Tests
        run: ./gradlew -DincludeTags="ComponentTest"

  End-To-End-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: End to End Integration Tests
        run: ./gradlew test -DincludeTags="EndToEndTest"

  API-Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: eclipse-edc/.github/.github/actions/setup-build@main
      - name: Component Tests
        run: ./gradlew test -DincludeTags="ApiTest"
